#Javier
#------------------------------------------------------------------

insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Mónica Roberto','Flores Martínez','TV 62 e No. 23-76','San Diego','Ibagué','Apartaestudio','Puente Aranda','MFloresM@unal.edu.co','Famisanar','Ciencias Económicas');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Natalia Isabel','Díaz Sánchez','CL 102 b No. 80-55','Guayabal','Cartagena','Casa','Suba','NDíazS@unal.edu.co','SaludTotal','Psicología');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Raúl Andrea','Silva Álvarez','KR 170 k No. 66-72','El Diamante','Cúcuta','Apartaestudio','Otra','RSilvaÁ@unal.edu.co','EPS Familiar','Ciencias Humanas');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('María Pedro','Silva Ortiz','AK 109 f No. 26-38','Santa Cruz','Bogotá','Finca','Suba','MSilvaO@unal.edu.co','Aliansalud','Ciencias Veterinarias y de Zootecnia');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Andrea Pedro','González Flores','KR 69 g No. 60-17','Castilla','Cartagena','Apartaestudio','Tunjuelito','AGonzálezF@unal.edu.co','Cafesalud','Medicina');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Lucía Mónica','Ramírez Rodríguez','AK 5 r No. 94-93','Belén','Bogotá','Casa','La Candelaria','LRamírezR@unal.edu.co','Famisanar','Ciencias Agrarias');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Pedro Laura','Núñez Chávez','CL 151 n No. 32-46','La Avanzada','Soacha','Finca','Los Mártires','PNúñezC@unal.edu.co','Sanitas','Ingeniería');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Pedro Luis','Morales Gómez','TV 103 l No. 35-93','Loma de Los Bernal','Medellín','Apartamento','Chapinero','PMoralesG@unal.edu.co','SaludTotal','Ingeniería');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Juan Jorge','Ruiz Ramírez','AC 10 n No. 7-77','Aranjuez','Villavicencio','Apartaestudio','Barrios Unidos','JRuizR@unal.edu.co','Sanitas','Ciencias Económicas');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Andrea Mónica','Cruz Hernández','AK 21 q No. 88-58','La Castellana','Villavicencio','Finca','Bosa','ACruzH@unal.edu.co','Nueva EPS','Ingeniería');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Isabel Gustavo','Álvarez Ortiz','AC 72 l No. 62-45','Santa Cruz','Bucaramanga','Apartamento','Santa Fe','IÁlvarezO@unal.edu.co','Nueva EPS','Medicina');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Pedro Juan','Flores Rojas','AK 125 s No. 84-16','San Antonio','Bogotá','Casa','Engativá','PFloresR@unal.edu.co','Compensar','Ciencias Económicas');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Andrea Gabriela','Mendoza Fernández','AK 100 r No. 81-98','Aranjuez','Medellín','Casa','San Cristóbal','AMendozaF@unal.edu.co','Nueva EPS','Odontología');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Manuel Raúl','García Hernández','KR 131 t No. 63-80','Manrique','Bogotá','Apartaestudio','Bosa','MGarcíaH@unal.edu.co','Cafesalud','Psicología');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Diego Roberto','Cruz Morales','AC 121 k No. 76-9','San Diego','Cali','Finca','Barrios Unidos','DCruzM@unal.edu.co','Colmedica','Psicología');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Raúl Natalia','García Morales','CL 69 f No. 42-10','El Popular','Medellín','Casa','Teusaquillo','RGarcíaM@unal.edu.co','Sanitas','Artes');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('José Natalia','Torres Álvarez','AC 139 g No. 39-2','La Mota','Cali','Finca','Usme','JTorresÁ@unal.edu.co','SaludTotal','Artes');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Felipe Gabriela','Fernández Martínez','TV 61 k No. 27-52','San Javier','Medellín','Finca','Ciudad Bolívar','FFernándezM@unal.edu.co','Sura EPS','Medicina');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Lucía Miguel','López Hernández','AC 83 b No. 8-55','El Poblado','Bucaramanga','Apartamento','Kennedy','LLópezH@unal.edu.co','Nueva EPS','Psicología');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Miguel Pedro','Torres Romero','AC 45 j No. 89-47','San Javier','Bogotá','Apartaestudio','Otra','MTorresR@unal.edu.co','Sanitas','Ingeniería');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Ernesto Luis','Rodríguez Ramírez','KR 30 l No. 95-10','El Lido','Ibagué','Apartaestudio','Rafael Uribe Uribe','ERodríguezR@unal.edu.co','Coomeva EPS','Derecho, Ciencias Políticas y Sociales');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Lucía Laura','Jiménez Álvarez','AC 34 i No. 7-36','El Chagualo','Medellín','Apartamento','La Candelaria','LJiménezÁ@unal.edu.co','Aliansalud','Ciencias Económicas');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Andrés Juan','Vargas Sánchez','KR 116 p No. 22-16','La Pradera','Cúcuta','Finca','Ciudad Bolívar','AVargasS@unal.edu.co','Coomeva EPS','Odontología');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Roberto Alejandro','Rojas Suárez','KR 161 l No. 64-26','Santa Cruz','Cali','Casa','Engativá','RRojasS@unal.edu.co','Colmedica','Medicina');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Carlos Ernesto','Vargas Hernández','CL 154 j No. 87-34','Bello','Soacha','Finca','Puente Aranda','CVargasH@unal.edu.co','Cafesalud','Ciencias Agrarias');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Carlos Mónica','Suárez Hernández','KR 27 m No. 65-89','Laureano Gómez','Villavicencio','Apartaestudio','Los Mártires','CSuárezH@unal.edu.co','EPS Familiar','Ciencias');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Ernesto Raúl','Mendoza Reyes','KR 77 g No. 12-72','Buenos Aires','Cali','Casa','Rafael Uribe Uribe','EMendozaR@unal.edu.co','SaludTotal','Enfermería');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Gabriela María','Torres Martínez','CL 70 d No. 88-40','Las Acacias','Bucaramanga','Apartamento','Usme','GTorresM@unal.edu.co','Sura EPS','Ingeniería');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Mario Carla','Gómez Chávez','AK 152 d No. 51-19','Moravia','Ibagué','Finca','Antonio Nariño','MGómezC@unal.edu.co','Nueva EPS','Ciencias Económicas');
insert into persona (perNombre,perApellido,perDireccion,perBarrio,perCiudad,perTipoVivienda,perLocalidad,perEmail,perEntidadSalud,perFacultad) values ('Alejandro Ana','López Hernández','KR 80 g No. 53-69','El Diamante','Bucaramanga','Apartamento','Barrios Unidos','ALópezH@unal.edu.co','SaludTotal','Ciencias');

#------------------------------------------------------------------
#------------------------------------------------------------------