-- MySQL Script generated by MySQL Workbench
-- Mon Mar 27 23:00:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`RecGeneralBienUniv`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RecGeneralBienUniv` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RecGeneralBienUniv` (
  `Docente_id` INT NOT NULL,
  `Periodo` INT NOT NULL,
  PRIMARY KEY (`Docente_id`),
  CONSTRAINT `fk_Decano_Docente1000`
    FOREIGN KEY (`Docente_id`)
    REFERENCES `mydb`.`Docente` (`docID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Decano_Docente1_idx` ON `mydb`.`RecGeneralBienUniv` (`Docente_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Vicerrector`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Vicerrector` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Vicerrector` (
  `idDocente` INT NOT NULL,
  `Periodo` INT NOT NULL,
  `idRector` INT NOT NULL,
  PRIMARY KEY (`idDocente`),
  CONSTRAINT `fk_Decano_Docente100`
    FOREIGN KEY (`idDocente`)
    REFERENCES `mydb`.`Docente` (`docID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vicerrector_RecGeneralBienUniv1`
    FOREIGN KEY (`idRector`)
    REFERENCES `mydb`.`RecGeneralBienUniv` (`Docente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Decano_Docente1_idx` ON `mydb`.`Vicerrector` (`idDocente` ASC) VISIBLE;

CREATE INDEX `fk_Vicerrector_RecGeneralBienUniv1_idx` ON `mydb`.`Vicerrector` (`idRector` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ComitNacDirectores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ComitNacDirectores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ComitNacDirectores` (
  `idComiNacDirectores` INT NOT NULL,
  `conBienAnoCreacion` INT NOT NULL,
  PRIMARY KEY (`idComiNacDirectores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DirectorBienestar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DirectorBienestar` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DirectorBienestar` (
  `docID` INT NOT NULL,
  `dirBienestarAnoInicio` INT NOT NULL,
  `dirBienestarNivel` ENUM("SEDE", "FACULTAD", "NACIONAL") NOT NULL,
  `comitNacDirectoresID` INT NOT NULL,
  `comitSedeDirectoresID` INT NOT NULL,
  PRIMARY KEY (`docID`),
  CONSTRAINT `fk_DirectorBienestar_Docente1`
    FOREIGN KEY (`docID`)
    REFERENCES `mydb`.`Docente` (`docID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DirectorBienestar_ComitNacDirectores1`
    FOREIGN KEY (`comitNacDirectoresID`)
    REFERENCES `mydb`.`ComitNacDirectores` (`idComiNacDirectores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DirectorBienestar_ComitSedeDirectores1`
    FOREIGN KEY (`comitSedeDirectoresID`)
    REFERENCES `mydb`.`ComitSedeDirectores` (`idComitSedeDirectores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_DirectorBienestar_Docente1_idx` ON `mydb`.`DirectorBienestar` (`docID` ASC) VISIBLE;

CREATE INDEX `fk_DirectorBienestar_ComitNacDirectores1_idx` ON `mydb`.`DirectorBienestar` (`comitNacDirectoresID` ASC) VISIBLE;

CREATE INDEX `fk_DirectorBienestar_ComitSedeDirectores1_idx` ON `mydb`.`DirectorBienestar` (`comitSedeDirectoresID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Estudiante` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Estudiante` (
  `estID` INT NOT NULL,
  `estCarrera` VARCHAR(45) NOT NULL,
  `estFacultad` VARCHAR(45) NOT NULL,
  `estPBM` TINYINT NOT NULL,
  `estTipoAdmision` VARCHAR(20) NOT NULL,
  `estEsEgresado` TINYINT NOT NULL,
  `estAnoGraduacion` INT NULL,
  `ReprEstudFacultad_Estudiante_id` INT NOT NULL,
  `ReprEstudSede_Estudiante_id` INT NOT NULL,
  PRIMARY KEY (`estID`),
  CONSTRAINT `fk_Estudiante_Persona1`
    FOREIGN KEY (`estID`)
    REFERENCES `mydb`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RepresentanteEmpleadosFacultad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RepresentanteEmpleadosFacultad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RepresentanteEmpleadosFacultad` (
  `Persona_idPersona` INT NOT NULL,
  `Facultad` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Persona_idPersona`),
  CONSTRAINT `fk_Gerente_Persona1000`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Gerente_Persona1_idx` ON `mydb`.`RepresentanteEmpleadosFacultad` (`Persona_idPersona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ComAsesorBienUnivFacult`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ComAsesorBienUnivFacult` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ComAsesorBienUnivFacult` (
  `idComAsesorBienUn` INT NOT NULL,
  `DirBienUnivSede_idComitSedeDirectores` INT NOT NULL,
  `Facultad` VARCHAR(45) NOT NULL,
  `Docente_Docente_id` INT NOT NULL,
  `RepresentanteEmpleadosFacultad_idPersona` INT NOT NULL,
  `directorBienestarID` INT NOT NULL,
  PRIMARY KEY (`idComAsesorBienUn`, `DirBienUnivSede_idComitSedeDirectores`),
  CONSTRAINT `fk_ComAsesorBienUnivFacult_Docente1`
    FOREIGN KEY (`Docente_Docente_id`)
    REFERENCES `mydb`.`Docente` (`docID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ComAsesorBienUnivFacult_RepresentanteEmpleadosFacultad1`
    FOREIGN KEY (`RepresentanteEmpleadosFacultad_idPersona`)
    REFERENCES `mydb`.`RepresentanteEmpleadosFacultad` (`Persona_idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ComAsesorBienUnivFacult_DirBienUnivSede1`
    FOREIGN KEY (`DirBienUnivSede_idComitSedeDirectores`)
    REFERENCES `mydb`.`DirBienUnivSede` (`dirBienSedeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ComAsesorBienUnivFacult_DirectorBienestar1`
    FOREIGN KEY (`directorBienestarID`)
    REFERENCES `mydb`.`DirectorBienestar` (`docID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ComAsesorBienUnivFacult_Docente1_idx` ON `mydb`.`ComAsesorBienUnivFacult` (`Docente_Docente_id` ASC) VISIBLE;

CREATE INDEX `fk_ComAsesorBienUnivFacult_RepresentanteEmpleadosFacultad1_idx` ON `mydb`.`ComAsesorBienUnivFacult` (`RepresentanteEmpleadosFacultad_idPersona` ASC) VISIBLE;

CREATE INDEX `fk_ComAsesorBienUnivFacult_DirBienUnivSede1_idx` ON `mydb`.`ComAsesorBienUnivFacult` (`DirBienUnivSede_idComitSedeDirectores` ASC) VISIBLE;

CREATE INDEX `fk_ComAsesorBienUnivFacult_DirectorBienestar1_idx` ON `mydb`.`ComAsesorBienUnivFacult` (`directorBienestarID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ReprEstudiantil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ReprEstudiantil` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ReprEstudiantil` (
  `estID` INT NOT NULL,
  `repEstNivel` ENUM("PREGRADO", "POSGRADO") NOT NULL,
  `resEstConsejoBienestarID` INT NULL,
  `repEstArea` ENUM("CARRERA", "FACULTAD", "SEDE", "CONSEJO") NOT NULL,
  `ComAsesorBienUnivFacult_idComAsesorBienUn` INT NULL,
  `comAsesorBienUnivFacult_DirBienUnivSede_idComitSedeDirectores` INT NULL,
  `comitSedeDirectoresID` INT NOT NULL,
  PRIMARY KEY (`estID`),
  CONSTRAINT `fk_ReprEstudiantil_ConBieneUniv1`
    FOREIGN KEY (`resEstConsejoBienestarID`)
    REFERENCES `mydb`.`ConBieneUniv` (`idConBieneUniv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ReprEstudiantil_Estudiante1`
    FOREIGN KEY (`estID`)
    REFERENCES `mydb`.`Estudiante` (`estID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ReprEstudiantil_ComAsesorBienUnivFacult1`
    FOREIGN KEY (`ComAsesorBienUnivFacult_idComAsesorBienUn` , `comAsesorBienUnivFacult_DirBienUnivSede_idComitSedeDirectores`)
    REFERENCES `mydb`.`ComAsesorBienUnivFacult` (`idComAsesorBienUn` , `DirBienUnivSede_idComitSedeDirectores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ReprEstudiantil_ComitSedeDirectores1`
    FOREIGN KEY (`comitSedeDirectoresID`)
    REFERENCES `mydb`.`ComitSedeDirectores` (`idComitSedeDirectores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ReprEstudiantil_ConBieneUniv1_idx` ON `mydb`.`ReprEstudiantil` (`resEstConsejoBienestarID` ASC) VISIBLE;

CREATE INDEX `fk_ReprEstudiantil_Estudiante1_idx` ON `mydb`.`ReprEstudiantil` (`estID` ASC) VISIBLE;

CREATE INDEX `fk_ReprEstudiantil_ComAsesorBienUnivFacult1_idx` ON `mydb`.`ReprEstudiantil` (`ComAsesorBienUnivFacult_idComAsesorBienUn` ASC, `comAsesorBienUnivFacult_DirBienUnivSede_idComitSedeDirectores` ASC) VISIBLE;

CREATE INDEX `fk_ReprEstudiantil_ComitSedeDirectores1_idx` ON `mydb`.`ReprEstudiantil` (`comitSedeDirectoresID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ComitNacMatricula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ComitNacMatricula` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ComitNacMatricula` (
  `idComiNacDirectores` INT NOT NULL,
  `Vicerrector_Docente_id` INT NOT NULL,
  `directorBienestarID` INT NOT NULL,
  `reprEstudiantilID` INT NOT NULL,
  PRIMARY KEY (`idComiNacDirectores`),
  CONSTRAINT `fk_ComitNacMatricula_Vicerrector1`
    FOREIGN KEY (`Vicerrector_Docente_id`)
    REFERENCES `mydb`.`Vicerrector` (`idDocente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ComitNacMatricula_DirectorBienestar1`
    FOREIGN KEY (`directorBienestarID`)
    REFERENCES `mydb`.`DirectorBienestar` (`docID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ComitNacMatricula_ReprEstudiantil1`
    FOREIGN KEY (`reprEstudiantilID`)
    REFERENCES `mydb`.`ReprEstudiantil` (`estID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ComitNacMatricula_Vicerrector1_idx` ON `mydb`.`ComitNacMatricula` (`Vicerrector_Docente_id` ASC) VISIBLE;

CREATE INDEX `fk_ComitNacMatricula_DirectorBienestar1_idx` ON `mydb`.`ComitNacMatricula` (`directorBienestarID` ASC) VISIBLE;

CREATE INDEX `fk_ComitNacMatricula_ReprEstudiantil1_idx` ON `mydb`.`ComitNacMatricula` (`reprEstudiantilID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Docente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Docente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Docente` (
  `docID` INT NOT NULL,
  `docTenerTarjeta` TINYINT NOT NULL,
  `docFacultad` VARCHAR(45) NOT NULL,
  `docEsRepprofesoral` TINYINT NOT NULL,
  `docEsDecano` TINYINT NOT NULL,
  `decPertConsejoBienestar` INT NULL,
  `comitNacMatriculaID` INT NULL,
  PRIMARY KEY (`docID`),
  CONSTRAINT `fk_Docente/Administrativo_Persona1`
    FOREIGN KEY (`docID`)
    REFERENCES `mydb`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Docente_ConBieneUniv1`
    FOREIGN KEY (`decPertConsejoBienestar`)
    REFERENCES `mydb`.`ConBieneUniv` (`idConBieneUniv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Docente_ComitNacMatricula1`
    FOREIGN KEY (`comitNacMatriculaID`)
    REFERENCES `mydb`.`ComitNacMatricula` (`idComiNacDirectores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Docente_ConBieneUniv1_idx` ON `mydb`.`Docente` (`decPertConsejoBienestar` ASC) VISIBLE;

CREATE INDEX `fk_Docente_ComitNacMatricula1_idx` ON `mydb`.`Docente` (`comitNacMatriculaID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ComitSedeDirectores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ComitSedeDirectores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ComitSedeDirectores` (
  `idComitSedeDirectores` INT NOT NULL,
  `comSedeDircAnoCreacion` INT NOT NULL,
  `docenteID` INT NOT NULL,
  `conBienestarID` INT NOT NULL,
  PRIMARY KEY (`idComitSedeDirectores`),
  CONSTRAINT `fk_ComitSedeDirectores_Docente1`
    FOREIGN KEY (`docenteID`)
    REFERENCES `mydb`.`Docente` (`docID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ComitSedeDirectores_ConBieneUniv1`
    FOREIGN KEY (`conBienestarID`)
    REFERENCES `mydb`.`ConBieneUniv` (`idConBieneUniv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ComitSedeDirectores_Docente1_idx` ON `mydb`.`ComitSedeDirectores` (`docenteID` ASC) VISIBLE;

CREATE INDEX `fk_ComitSedeDirectores_ConBieneUniv1_idx` ON `mydb`.`ComitSedeDirectores` (`conBienestarID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`DirBienUnivSede`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DirBienUnivSede` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DirBienUnivSede` (
  `dirBienSedeID` INT NOT NULL,
  `comitSedeDirectoresID` INT NOT NULL,
  `Sede` VARCHAR(45) NOT NULL,
  `DirectorBienestarID` INT NOT NULL,
  PRIMARY KEY (`dirBienSedeID`, `comitSedeDirectoresID`),
  CONSTRAINT `fk_DirBienUnivSede_ComitSedeDirectores2`
    FOREIGN KEY (`comitSedeDirectoresID`)
    REFERENCES `mydb`.`ComitSedeDirectores` (`idComitSedeDirectores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DirBienUnivSede_DirectorBienestar1`
    FOREIGN KEY (`DirectorBienestarID`)
    REFERENCES `mydb`.`DirectorBienestar` (`docID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_DirBienUnivSede_ComitSedeDirectores2_idx` ON `mydb`.`DirBienUnivSede` (`comitSedeDirectoresID` ASC) VISIBLE;

CREATE INDEX `fk_DirBienUnivSede_DirectorBienestar1_idx` ON `mydb`.`DirBienUnivSede` (`DirectorBienestarID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Gerente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Gerente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Gerente` (
  `perID` INT NOT NULL,
  `Dependencia` VARCHAR(30) NOT NULL,
  `dirBienestarSedeID` INT NOT NULL,
  PRIMARY KEY (`perID`),
  CONSTRAINT `fk_Gerente_Persona10`
    FOREIGN KEY (`perID`)
    REFERENCES `mydb`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gerente_DirBienUnivSede1`
    FOREIGN KEY (`dirBienestarSedeID`)
    REFERENCES `mydb`.`DirBienUnivSede` (`dirBienSedeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Gerente_Persona1_idx` ON `mydb`.`Gerente` (`perID` ASC) VISIBLE;

CREATE INDEX `fk_Gerente_DirBienUnivSede1_idx` ON `mydb`.`Gerente` (`dirBienestarSedeID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ConBieneUniv`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ConBieneUniv` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ConBieneUniv` (
  `idConBieneUniv` INT NOT NULL,
  `conBienAnoCreacion` INT NOT NULL,
  `estEgresadoID` INT NOT NULL,
  `dirBienestarID` INT NOT NULL,
  `geNacFinanAdminID` INT NOT NULL,
  `vicerrectorID` INT NOT NULL,
  `comNacDirectoresID` INT NOT NULL,
  `comnacMatriculaID` INT NOT NULL,
  PRIMARY KEY (`idConBieneUniv`),
  CONSTRAINT `fk_ConBieneUniv_Gerente1`
    FOREIGN KEY (`geNacFinanAdminID`)
    REFERENCES `mydb`.`Gerente` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConBieneUniv_Vicerrector1`
    FOREIGN KEY (`vicerrectorID`)
    REFERENCES `mydb`.`Vicerrector` (`idDocente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConBieneUniv_ComiNacDirectores1`
    FOREIGN KEY (`comNacDirectoresID`)
    REFERENCES `mydb`.`ComitNacDirectores` (`idComiNacDirectores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConBieneUniv_ComitNacMatricula1`
    FOREIGN KEY (`comnacMatriculaID`)
    REFERENCES `mydb`.`ComitNacMatricula` (`idComiNacDirectores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConBieneUniv_Estudiante1`
    FOREIGN KEY (`estEgresadoID`)
    REFERENCES `mydb`.`Estudiante` (`estID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConBieneUniv_DirectorBienestar1`
    FOREIGN KEY (`dirBienestarID`)
    REFERENCES `mydb`.`DirectorBienestar` (`docID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ConBieneUniv_Gerente1_idx` ON `mydb`.`ConBieneUniv` (`geNacFinanAdminID` ASC) VISIBLE;

CREATE INDEX `fk_ConBieneUniv_Vicerrector1_idx` ON `mydb`.`ConBieneUniv` (`vicerrectorID` ASC) VISIBLE;

CREATE INDEX `fk_ConBieneUniv_ComiNacDirectores1_idx` ON `mydb`.`ConBieneUniv` (`comNacDirectoresID` ASC) VISIBLE;

CREATE INDEX `fk_ConBieneUniv_ComitNacMatricula1_idx` ON `mydb`.`ConBieneUniv` (`comnacMatriculaID` ASC) VISIBLE;

CREATE INDEX `fk_ConBieneUniv_Estudiante1_idx` ON `mydb`.`ConBieneUniv` (`estEgresadoID` ASC) VISIBLE;

CREATE INDEX `fk_ConBieneUniv_DirectorBienestar1_idx` ON `mydb`.`ConBieneUniv` (`dirBienestarID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`TiendaBienestarUN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TiendaBienestarUN` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TiendaBienestarUN` (
  `idTiendaBienestarUN` INT NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(50) NOT NULL,
  `Horario` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Director_idPersona` INT NOT NULL,
  `Coordiandor_idPersona1` INT NOT NULL,
  `ConBieneUniv_idConBieneUniv` INT NOT NULL,
  PRIMARY KEY (`idTiendaBienestarUN`),
  CONSTRAINT `fk_TiendaBienestarUN_Persona1`
    FOREIGN KEY (`Director_idPersona`)
    REFERENCES `mydb`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TiendaBienestarUN_Persona2`
    FOREIGN KEY (`Coordiandor_idPersona1`)
    REFERENCES `mydb`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TiendaBienestarUN_ConBieneUniv1`
    FOREIGN KEY (`ConBieneUniv_idConBieneUniv`)
    REFERENCES `mydb`.`ConBieneUniv` (`idConBieneUniv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TiendaBienestarUN_Persona1_idx` ON `mydb`.`TiendaBienestarUN` (`Director_idPersona` ASC) VISIBLE;

CREATE INDEX `fk_TiendaBienestarUN_Persona2_idx` ON `mydb`.`TiendaBienestarUN` (`Coordiandor_idPersona1` ASC) VISIBLE;

CREATE INDEX `fk_TiendaBienestarUN_ConBieneUniv1_idx` ON `mydb`.`TiendaBienestarUN` (`ConBieneUniv_idConBieneUniv` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Actividad Física y Deportes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Actividad Física y Deportes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Actividad Física y Deportes` (
  `idArea` INT NOT NULL,
  `nombreArea` INT NOT NULL,
  `TelefonoContacto` INT NOT NULL,
  `Extensión` INT NOT NULL,
  `CorreoElectrónico` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idArea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AcompañamientoIntegral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AcompañamientoIntegral` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AcompañamientoIntegral` (
  `idNombreArea` INT NOT NULL,
  `TelefonoContacto` INT NOT NULL,
  `Extensión` INT NOT NULL,
  `CorreoElectrónico` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idNombreArea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Persona` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `perID` INT NOT NULL,
  `perNombre` VARCHAR(45) NOT NULL,
  `perApellido` VARCHAR(45) NOT NULL,
  `perDireccion` VARCHAR(45) NOT NULL,
  `perBarrio` VARCHAR(45) NOT NULL,
  `perCiudad` VARCHAR(45) NOT NULL,
  `perTipoVivienda` ENUM("Casa", "Apartamento", "Apartaestudio", "Finca") NOT NULL,
  `perLocalidad` VARCHAR(45) NOT NULL,
  `perEmail` VARCHAR(20) NOT NULL,
  `perEntidadSalud` VARCHAR(45) NOT NULL,
  `perProcedencia` VARCHAR(45) NOT NULL,
  `perSede` VARCHAR(20) NOT NULL,
  `perIDTrabTienda` INT NULL,
  `perPartiActidFisDep` INT NULL,
  `perIDAcompaIntegral` INT NULL,
  PRIMARY KEY (`perID`),
  CONSTRAINT `fk_Persona_TiendaBienestarUN1`
    FOREIGN KEY (`perIDTrabTienda`)
    REFERENCES `mydb`.`TiendaBienestarUN` (`idTiendaBienestarUN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Actividad Física y Deportes1`
    FOREIGN KEY (`perPartiActidFisDep`)
    REFERENCES `mydb`.`Actividad Física y Deportes` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_AcompañamientoIntegral1`
    FOREIGN KEY (`perIDAcompaIntegral`)
    REFERENCES `mydb`.`AcompañamientoIntegral` (`idNombreArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Persona_TiendaBienestarUN1_idx` ON `mydb`.`Persona` (`perIDTrabTienda` ASC) VISIBLE;

CREATE INDEX `fk_Persona_Actividad Física y Deportes1_idx` ON `mydb`.`Persona` (`perPartiActidFisDep` ASC) VISIBLE;

CREATE INDEX `fk_Persona_AcompañamientoIntegral1_idx` ON `mydb`.`Persona` (`perIDAcompaIntegral` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Ambulancia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ambulancia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ambulancia` (
  `idAmbulancia` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`idAmbulancia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PersonalSalud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PersonalSalud` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PersonalSalud` (
  `Persona_id` INT NOT NULL,
  `salProfesion` VARCHAR(45) NULL,
  `salEspecializacion` VARCHAR(45) NULL,
  `salTipo` VARCHAR(10) NOT NULL,
  `Ambulancia_id` VARCHAR(6) NULL,
  PRIMARY KEY (`Persona_id`),
  CONSTRAINT `fk_PersonalSalud_Persona`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `mydb`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PersonalSalud_Ambulancia1`
    FOREIGN KEY (`Ambulancia_id`)
    REFERENCES `mydb`.`Ambulancia` (`idAmbulancia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PersonalSalud_Ambulancia1_idx` ON `mydb`.`PersonalSalud` (`Ambulancia_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Urgencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Urgencia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Urgencia` (
  `Persona_id` INT NOT NULL,
  `Ambulancia` VARCHAR(6) NOT NULL,
  `idUrgencia` INT NOT NULL,
  `urgFecha` DATETIME NOT NULL,
  `urgTipo` TINYINT NOT NULL,
  `urgRiesgo` TINYINT NOT NULL,
  `urgDiagnostico` VARCHAR(45) NOT NULL,
  `urgTraslado` VARCHAR(45) NOT NULL,
  `urgHoraRecogida` DATETIME NOT NULL,
  `urgHoraDejada` DATETIME NOT NULL,
  PRIMARY KEY (`Persona_id`),
  CONSTRAINT `fk_Urgencia_Ambulancia1`
    FOREIGN KEY (`Ambulancia`)
    REFERENCES `mydb`.`Ambulancia` (`idAmbulancia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Urgencia_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `mydb`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Urgencia_Ambulancia1_idx` ON `mydb`.`Urgencia` (`Ambulancia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Incapacidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Incapacidad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Incapacidad` (
  `Persona_id` INT NOT NULL,
  `incFecha` DATE NOT NULL,
  `incEnfermedad` VARCHAR(45) NOT NULL,
  `incDias` TINYINT NOT NULL,
  `incConvalidada` BIT NOT NULL,
  `incSoporteAddress` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`Persona_id`),
  CONSTRAINT `fk_Incapacidad_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `mydb`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PerfilRiesgoIntegral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PerfilRiesgoIntegral` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PerfilRiesgoIntegral` (
  `Persona_id` INT NOT NULL,
  `perFecha` DATE NOT NULL,
  PRIMARY KEY (`Persona_id`),
  CONSTRAINT `fk_PerfilRiesgoIntegral_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `mydb`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Resultados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Resultados` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Resultados` (
  `PerfilRiesgoIntegral_id` INT NOT NULL,
  `resPregunta` VARCHAR(45) NOT NULL,
  `resRespuesta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PerfilRiesgoIntegral_id`),
  CONSTRAINT `fk_Resultados_PerfilRiesgoIntegral1`
    FOREIGN KEY (`PerfilRiesgoIntegral_id`)
    REFERENCES `mydb`.`PerfilRiesgoIntegral` (`Persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AtencionEnSalud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AtencionEnSalud` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AtencionEnSalud` (
  `Persona_id` INT NOT NULL,
  `ateFecha` DATETIME NOT NULL,
  `ateSoporteAddress` VARCHAR(32) NOT NULL,
  `disVerificado` BIT NOT NULL,
  PRIMARY KEY (`Persona_id`),
  CONSTRAINT `fk_AtencionEnSalud_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `mydb`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Discapacidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Discapacidad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Discapacidad` (
  `Persona_id` INT NOT NULL,
  `disNombre` VARCHAR(45) NOT NULL,
  `disSoporteAddress` VARCHAR(32) NOT NULL,
  `disVerificado` BIT NOT NULL,
  PRIMARY KEY (`Persona_id`),
  CONSTRAINT `fk_Discapacidad_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `mydb`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AsesoriaAseguramientoSalud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AsesoriaAseguramientoSalud` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AsesoriaAseguramientoSalud` (
  `Persona_id` INT NOT NULL,
  `aseFecha` DATE NOT NULL,
  `aseResultado` VARCHAR(45) NOT NULL,
  `aseDescripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Persona_id`),
  CONSTRAINT `fk_AsesoriaAseguramientoSalud_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `mydb`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HistoriaClinica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`HistoriaClinica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`HistoriaClinica` (
  `Persona_id` INT NOT NULL,
  `hisFechaApertura` DATE NOT NULL,
  PRIMARY KEY (`Persona_id`),
  CONSTRAINT `fk_HistoriaClinica_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `mydb`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_HistoriaClinica_Persona1_idx` ON `mydb`.`HistoriaClinica` (`Persona_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`CitaMedica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CitaMedica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CitaMedica` (
  `idCitaMedica` INT NOT NULL,
  `Doctor` INT NOT NULL,
  `Paciente` INT NOT NULL,
  `citFecha` DATETIME NOT NULL,
  `citEspecialidad` VARCHAR(45) NOT NULL,
  `citDiagnostico` VARCHAR(80) NULL,
  `HistoriaClinica_id` INT NOT NULL,
  PRIMARY KEY (`idCitaMedica`),
  CONSTRAINT `fk_CitaMedica_PersonalSalud1`
    FOREIGN KEY (`Doctor`)
    REFERENCES `mydb`.`PersonalSalud` (`Persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CitaMedica_Persona1`
    FOREIGN KEY (`Paciente`)
    REFERENCES `mydb`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CitaMedica_HistoriaClinica1`
    FOREIGN KEY (`HistoriaClinica_id`)
    REFERENCES `mydb`.`HistoriaClinica` (`Persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CitaMedica_PersonalSalud1_idx` ON `mydb`.`CitaMedica` (`Doctor` ASC) VISIBLE;

CREATE INDEX `fk_CitaMedica_Persona1_idx` ON `mydb`.`CitaMedica` (`Paciente` ASC) VISIBLE;

CREATE INDEX `fk_CitaMedica_HistoriaClinica1_idx` ON `mydb`.`CitaMedica` (`HistoriaClinica_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`EvaluacionFisica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EvaluacionFisica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EvaluacionFisica` (
  `CitaMedica_id` INT NOT NULL,
  `evaPeso` TINYINT NOT NULL,
  `evaEstatura` TINYINT NOT NULL,
  `evaRitmoCardiaco` TINYINT NOT NULL,
  `evaVision` TINYINT NOT NULL,
  PRIMARY KEY (`CitaMedica_id`),
  CONSTRAINT `fk_EvaluacionFisica_CitaMedica1`
    FOREIGN KEY (`CitaMedica_id`)
    REFERENCES `mydb`.`CitaMedica` (`idCitaMedica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medicamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Medicamentos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Medicamentos` (
  `CitaMedica_id` INT NOT NULL,
  `medNombre` VARCHAR(45) NOT NULL,
  `medCantidad` TINYINT NOT NULL,
  `medIntervalos` TINYINT NOT NULL,
  PRIMARY KEY (`CitaMedica_id`),
  CONSTRAINT `fk_Medicamentos_CitaMedica1`
    FOREIGN KEY (`CitaMedica_id`)
    REFERENCES `mydb`.`CitaMedica` (`idCitaMedica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrdenMedica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`OrdenMedica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`OrdenMedica` (
  `CitaMedica_id` INT NOT NULL,
  `ordExamen` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CitaMedica_id`),
  CONSTRAINT `fk_OrdenMedica_CitaMedica1`
    FOREIGN KEY (`CitaMedica_id`)
    REFERENCES `mydb`.`CitaMedica` (`idCitaMedica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AntecedentesFamiliares`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AntecedentesFamiliares` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AntecedentesFamiliares` (
  `HistoriaClinica_id` INT NOT NULL,
  `antFamiliar` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`HistoriaClinica_id`),
  CONSTRAINT `fk_AntecedentesFamiliares_HistoriaClinica1`
    FOREIGN KEY (`HistoriaClinica_id`)
    REFERENCES `mydb`.`HistoriaClinica` (`Persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Enfermedad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Enfermedad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Enfermedad` (
  `HistoriaClinica_id` INT NOT NULL,
  `enfNombre` VARCHAR(45) NOT NULL,
  `enfFechaInicio` DATE NOT NULL,
  PRIMARY KEY (`HistoriaClinica_id`),
  CONSTRAINT `fk_Enfermedad_HistoriaClinica1`
    FOREIGN KEY (`HistoriaClinica_id`)
    REFERENCES `mydb`.`HistoriaClinica` (`Persona_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EnfermedadesDeFamiliares`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EnfermedadesDeFamiliares` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EnfermedadesDeFamiliares` (
  `Enfermedad_id` INT NOT NULL,
  `AntecedentesFamiliares_id` INT NOT NULL,
  PRIMARY KEY (`Enfermedad_id`, `AntecedentesFamiliares_id`),
  CONSTRAINT `fk_Enfermedad_has_AntecedentesFamiliares_Enfermedad1`
    FOREIGN KEY (`Enfermedad_id`)
    REFERENCES `mydb`.`Enfermedad` (`HistoriaClinica_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enfermedad_has_AntecedentesFamiliares_AntecedentesFamiliar1`
    FOREIGN KEY (`AntecedentesFamiliares_id`)
    REFERENCES `mydb`.`AntecedentesFamiliares` (`HistoriaClinica_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Enfermedad_has_AntecedentesFamiliares_AntecedentesFamili_idx` ON `mydb`.`EnfermedadesDeFamiliares` (`AntecedentesFamiliares_id` ASC) VISIBLE;

CREATE INDEX `fk_Enfermedad_has_AntecedentesFamiliares_Enfermedad1_idx` ON `mydb`.`EnfermedadesDeFamiliares` (`Enfermedad_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Actividad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Actividad` (
  `idActividad` INT NOT NULL,
  `actTipo` VARCHAR(45) NOT NULL,
  `actFecha` DATETIME NOT NULL,
  `actAlcance` INT NOT NULL,
  `actPresupuesto` INT NOT NULL,
  `actDescripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idActividad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ActividadOrganizadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ActividadOrganizadores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ActividadOrganizadores` (
  `Actividad_id` INT NOT NULL,
  `Organizador_id` INT NOT NULL,
  PRIMARY KEY (`Actividad_id`, `Organizador_id`),
  CONSTRAINT `fk_Actividad_has_Persona_Actividad1`
    FOREIGN KEY (`Actividad_id`)
    REFERENCES `mydb`.`Actividad` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_has_Persona_Persona1`
    FOREIGN KEY (`Organizador_id`)
    REFERENCES `mydb`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Actividad_has_Persona_Persona1_idx` ON `mydb`.`ActividadOrganizadores` (`Organizador_id` ASC) VISIBLE;

CREATE INDEX `fk_Actividad_has_Persona_Actividad1_idx` ON `mydb`.`ActividadOrganizadores` (`Actividad_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ActividadParticipantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ActividadParticipantes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ActividadParticipantes` (
  `Actividad_id` INT NOT NULL,
  `Participante_id` INT NOT NULL,
  PRIMARY KEY (`Actividad_id`, `Participante_id`),
  CONSTRAINT `fk_Actividad_has_Persona_Actividad2`
    FOREIGN KEY (`Actividad_id`)
    REFERENCES `mydb`.`Actividad` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_has_Persona_Persona2`
    FOREIGN KEY (`Participante_id`)
    REFERENCES `mydb`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Actividad_has_Persona_Persona2_idx` ON `mydb`.`ActividadParticipantes` (`Participante_id` ASC) VISIBLE;

CREATE INDEX `fk_Actividad_has_Persona_Actividad2_idx` ON `mydb`.`ActividadParticipantes` (`Actividad_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`PEAMA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PEAMA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PEAMA` (
  `Estudiante_id` INT NOT NULL,
  `peaEtapa` TINYINT NOT NULL,
  PRIMARY KEY (`Estudiante_id`),
  CONSTRAINT `fk_PEAMA_Estudiante1`
    FOREIGN KEY (`Estudiante_id`)
    REFERENCES `mydb`.`Estudiante` (`estID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TarjetaPremiumPass`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TarjetaPremiumPass` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TarjetaPremiumPass` (
  `Docente_id` INT NOT NULL,
  `tarSaldo` INT NOT NULL,
  `tarActivada` BIT NOT NULL,
  PRIMARY KEY (`Docente_id`),
  CONSTRAINT `fk_table1_Docente1`
    FOREIGN KEY (`Docente_id`)
    REFERENCES `mydb`.`Docente` (`docID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movimientos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Movimientos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Movimientos` (
  `TarjetaPremiumPass_id` INT NOT NULL,
  `movFecha` DATETIME NOT NULL,
  `movEstablecimiento` VARCHAR(45) NOT NULL,
  `movMonto` INT NOT NULL,
  PRIMARY KEY (`TarjetaPremiumPass_id`),
  CONSTRAINT `fk_Movimientos_TarjetaPremiumPass1`
    FOREIGN KEY (`TarjetaPremiumPass_id`)
    REFERENCES `mydb`.`TarjetaPremiumPass` (`Docente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Publicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Publicacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Publicacion` (
  `idPublicacion` INT NOT NULL,
  `pubTitulo` VARCHAR(45) NOT NULL,
  `pubFechaPublicacion` DATE NOT NULL,
  `pubTipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPublicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PersonaEscribir`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PersonaEscribir` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PersonaEscribir` (
  `Persona_idPersona` INT NOT NULL,
  `Publicacion_idPublicacion` INT NOT NULL,
  PRIMARY KEY (`Persona_idPersona`, `Publicacion_idPublicacion`),
  CONSTRAINT `fk_Persona_has_Publicacion_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_has_Publicacion_Publicacion1`
    FOREIGN KEY (`Publicacion_idPublicacion`)
    REFERENCES `mydb`.`Publicacion` (`idPublicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Persona_has_Publicacion_Publicacion1_idx` ON `mydb`.`PersonaEscribir` (`Publicacion_idPublicacion` ASC) VISIBLE;

CREATE INDEX `fk_Persona_has_Publicacion_Persona1_idx` ON `mydb`.`PersonaEscribir` (`Persona_idPersona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`JefeBienestar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`JefeBienestar` ;

CREATE TABLE IF NOT EXISTS `mydb`.`JefeBienestar` (
  `perID` INT NOT NULL,
  `Dependencia` VARCHAR(30) NOT NULL,
  `jefEsJuridico` TINYINT NOT NULL,
  `jefEsPlaneacion` TINYINT NOT NULL,
  `gerenteID` INT NOT NULL,
  `comiNacDirectoresID` INT NOT NULL,
  `DirBienSedeID` INT NOT NULL,
  `comitNacMatriculaID` INT NULL,
  PRIMARY KEY (`perID`),
  CONSTRAINT `fk_Gerente_Persona1`
    FOREIGN KEY (`perID`)
    REFERENCES `mydb`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jefe Bienestar_Gerente1`
    FOREIGN KEY (`gerenteID`)
    REFERENCES `mydb`.`Gerente` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JefeBienestar_ComiNacDirectores1`
    FOREIGN KEY (`comiNacDirectoresID`)
    REFERENCES `mydb`.`ComitNacDirectores` (`idComiNacDirectores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JefeBienestar_DirBienUnivSede1`
    FOREIGN KEY (`DirBienSedeID`)
    REFERENCES `mydb`.`DirBienUnivSede` (`dirBienSedeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JefeBienestar_ComitNacMatricula2`
    FOREIGN KEY (`comitNacMatriculaID`)
    REFERENCES `mydb`.`ComitNacMatricula` (`idComiNacDirectores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Gerente_Persona1_idx` ON `mydb`.`JefeBienestar` (`perID` ASC) VISIBLE;

CREATE INDEX `fk_Jefe Bienestar_Gerente1_idx` ON `mydb`.`JefeBienestar` (`gerenteID` ASC) VISIBLE;

CREATE INDEX `fk_JefeBienestar_ComiNacDirectores1_idx` ON `mydb`.`JefeBienestar` (`comiNacDirectoresID` ASC) VISIBLE;

CREATE INDEX `fk_JefeBienestar_DirBienUnivSede1_idx` ON `mydb`.`JefeBienestar` (`DirBienSedeID` ASC) VISIBLE;

CREATE INDEX `fk_JefeBienestar_ComitNacMatricula2_idx` ON `mydb`.`JefeBienestar` (`comitNacMatriculaID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Funcionario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `Persona_idPersona` INT NOT NULL,
  `Dependencia` VARCHAR(30) NOT NULL,
  `Representante Empleados Facultad_Persona_idPersona` INT NOT NULL,
  `DirBienUnivSede_idComitSedeDirectores` INT NOT NULL,
  PRIMARY KEY (`Persona_idPersona`),
  CONSTRAINT `fk_Gerente_Persona100`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Representante Empleados Facultad1`
    FOREIGN KEY (`Representante Empleados Facultad_Persona_idPersona`)
    REFERENCES `mydb`.`RepresentanteEmpleadosFacultad` (`Persona_idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_DirBienUnivSede1`
    FOREIGN KEY (`DirBienUnivSede_idComitSedeDirectores`)
    REFERENCES `mydb`.`DirBienUnivSede` (`dirBienSedeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Gerente_Persona1_idx` ON `mydb`.`Funcionario` (`Persona_idPersona` ASC) VISIBLE;

CREATE INDEX `fk_Funcionario_Representante Empleados Facultad1_idx` ON `mydb`.`Funcionario` (`Representante Empleados Facultad_Persona_idPersona` ASC) VISIBLE;

CREATE INDEX `fk_Funcionario_DirBienUnivSede1_idx` ON `mydb`.`Funcionario` (`DirBienUnivSede_idComitSedeDirectores` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`DirAcademico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DirAcademico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DirAcademico` (
  `Docente_id` INT NOT NULL,
  `ComitSedeDirectoresID` INT NOT NULL,
  PRIMARY KEY (`Docente_id`),
  CONSTRAINT `fk_Decano_Docente100000`
    FOREIGN KEY (`Docente_id`)
    REFERENCES `mydb`.`Docente` (`docID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DirAcademico_ComitSedeDirectores1`
    FOREIGN KEY (`ComitSedeDirectoresID`)
    REFERENCES `mydb`.`ComitSedeDirectores` (`idComitSedeDirectores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Decano_Docente1_idx` ON `mydb`.`DirAcademico` (`Docente_id` ASC) VISIBLE;

CREATE INDEX `fk_DirAcademico_ComitSedeDirectores1_idx` ON `mydb`.`DirAcademico` (`ComitSedeDirectoresID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Normatividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Normatividad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Normatividad` (
  `idNormatividad` INT NOT NULL,
  `ConBieneID` INT NULL,
  `ComiNacDirectoresID` INT NULL,
  `ComitSedeDirectoresID` INT NULL,
  `ComitNacMatriculaID` INT NULL,
  `norDescripcion` VARCHAR(45) NOT NULL,
  `norTipo` VARCHAR(15) NOT NULL,
  `norAño` TINYINT NOT NULL,
  `norNumero` TINYINT NOT NULL,
  `norFechaEntradaVigencia` DATE NOT NULL,
  `norLink` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idNormatividad`),
  CONSTRAINT `fk_Normatividad_ConBieneUniv1`
    FOREIGN KEY (`ConBieneID`)
    REFERENCES `mydb`.`ConBieneUniv` (`idConBieneUniv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Normatividad_ComiNacDirectores1`
    FOREIGN KEY (`ComiNacDirectoresID`)
    REFERENCES `mydb`.`ComitNacDirectores` (`idComiNacDirectores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Normatividad_ComitSedeDirectores1`
    FOREIGN KEY (`ComitSedeDirectoresID`)
    REFERENCES `mydb`.`ComitSedeDirectores` (`idComitSedeDirectores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Normatividad_ComitNacMatricula1`
    FOREIGN KEY (`ComitNacMatriculaID`)
    REFERENCES `mydb`.`ComitNacMatricula` (`idComiNacDirectores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Normatividad_ConBieneUniv1_idx` ON `mydb`.`Normatividad` (`ConBieneID` ASC) VISIBLE;

CREATE INDEX `fk_Normatividad_ComiNacDirectores1_idx` ON `mydb`.`Normatividad` (`ComiNacDirectoresID` ASC) VISIBLE;

CREATE INDEX `fk_Normatividad_ComitSedeDirectores1_idx` ON `mydb`.`Normatividad` (`ComitSedeDirectoresID` ASC) VISIBLE;

CREATE INDEX `fk_Normatividad_ComitNacMatricula1_idx` ON `mydb`.`Normatividad` (`ComitNacMatriculaID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`DirBienUnivSede_has_Normatividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DirBienUnivSede_has_Normatividad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DirBienUnivSede_has_Normatividad` (
  `DirBienUnivSede_idComitSedeDirectores` INT NOT NULL,
  `Normatividad_idNormatividad` INT NOT NULL,
  PRIMARY KEY (`DirBienUnivSede_idComitSedeDirectores`, `Normatividad_idNormatividad`),
  CONSTRAINT `fk_DirBienUnivSede_has_Normatividad_DirBienUnivSede1`
    FOREIGN KEY (`DirBienUnivSede_idComitSedeDirectores`)
    REFERENCES `mydb`.`DirBienUnivSede` (`dirBienSedeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DirBienUnivSede_has_Normatividad_Normatividad1`
    FOREIGN KEY (`Normatividad_idNormatividad`)
    REFERENCES `mydb`.`Normatividad` (`idNormatividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_DirBienUnivSede_has_Normatividad_Normatividad1_idx` ON `mydb`.`DirBienUnivSede_has_Normatividad` (`Normatividad_idNormatividad` ASC) VISIBLE;

CREATE INDEX `fk_DirBienUnivSede_has_Normatividad_DirBienUnivSede1_idx` ON `mydb`.`DirBienUnivSede_has_Normatividad` (`DirBienUnivSede_idComitSedeDirectores` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Normatividad_has_ComAsesorBienUnivFacult`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Normatividad_has_ComAsesorBienUnivFacult` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Normatividad_has_ComAsesorBienUnivFacult` (
  `Normatividad_idNormatividad` INT NOT NULL,
  `ComAsesorBienUnivFacult_idComAsesorBienUnivcol` INT NOT NULL,
  PRIMARY KEY (`Normatividad_idNormatividad`, `ComAsesorBienUnivFacult_idComAsesorBienUnivcol`),
  CONSTRAINT `fk_Normatividad_has_ComAsesorBienUnivFacult_Normatividad1`
    FOREIGN KEY (`Normatividad_idNormatividad`)
    REFERENCES `mydb`.`Normatividad` (`idNormatividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Normatividad_has_ComAsesorBienUnivFacult_ComAsesorBienUniv1`
    FOREIGN KEY (`ComAsesorBienUnivFacult_idComAsesorBienUnivcol`)
    REFERENCES `mydb`.`ComAsesorBienUnivFacult` (`idComAsesorBienUn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Normatividad_has_ComAsesorBienUnivFacult_ComAsesorBienUn_idx` ON `mydb`.`Normatividad_has_ComAsesorBienUnivFacult` (`ComAsesorBienUnivFacult_idComAsesorBienUnivcol` ASC) VISIBLE;

CREATE INDEX `fk_Normatividad_has_ComAsesorBienUnivFacult_Normatividad1_idx` ON `mydb`.`Normatividad_has_ComAsesorBienUnivFacult` (`Normatividad_idNormatividad` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`EventoCultural`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EventoCultural` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EventoCultural` (
  `idEventoCultural` INT NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Lugar` VARCHAR(45) NOT NULL,
  `Fecha` DATE NOT NULL,
  `horaInicio` TIME NOT NULL,
  `horaFin` TIME NOT NULL,
  `Tipo` ENUM("Evento", "Actividad Lúdica", "Instrucción", "Promoción Interculturalidad", "Expresión Talentos") NOT NULL,
  `Descripcion` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idEventoCultural`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EventoCultural_gestiona_Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EventoCultural_gestiona_Persona` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EventoCultural_gestiona_Persona` (
  `EventoCultural_idEventoCultural` INT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EventoCultural_idEventoCultural`, `Persona_idPersona`),
  CONSTRAINT `fk_EventoCultural_has_Persona_EventoCultural1`
    FOREIGN KEY (`EventoCultural_idEventoCultural`)
    REFERENCES `mydb`.`EventoCultural` (`idEventoCultural`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EventoCultural_has_Persona_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_EventoCultural_has_Persona_Persona1_idx` ON `mydb`.`EventoCultural_gestiona_Persona` (`Persona_idPersona` ASC) VISIBLE;

CREATE INDEX `fk_EventoCultural_has_Persona_EventoCultural1_idx` ON `mydb`.`EventoCultural_gestiona_Persona` (`EventoCultural_idEventoCultural` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`EventoCultural_asistir_Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EventoCultural_asistir_Persona` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EventoCultural_asistir_Persona` (
  `EventoCultural_idEventoCultural` INT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  `Comentario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EventoCultural_idEventoCultural`, `Persona_idPersona`),
  CONSTRAINT `fk_EventoCultural_has_Persona_EventoCultural2`
    FOREIGN KEY (`EventoCultural_idEventoCultural`)
    REFERENCES `mydb`.`EventoCultural` (`idEventoCultural`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EventoCultural_has_Persona_Persona2`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_EventoCultural_has_Persona_Persona2_idx` ON `mydb`.`EventoCultural_asistir_Persona` (`Persona_idPersona` ASC) VISIBLE;

CREATE INDEX `fk_EventoCultural_has_Persona_EventoCultural2_idx` ON `mydb`.`EventoCultural_asistir_Persona` (`EventoCultural_idEventoCultural` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`EventoCultural_participar_Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EventoCultural_participar_Persona` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EventoCultural_participar_Persona` (
  `EventoCultural_idEventoCultural` INT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  `Talento/Actividad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EventoCultural_idEventoCultural`, `Persona_idPersona`),
  CONSTRAINT `fk_EventoCultural_has_Persona_EventoCultural3`
    FOREIGN KEY (`EventoCultural_idEventoCultural`)
    REFERENCES `mydb`.`EventoCultural` (`idEventoCultural`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EventoCultural_has_Persona_Persona3`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_EventoCultural_has_Persona_Persona3_idx` ON `mydb`.`EventoCultural_participar_Persona` (`Persona_idPersona` ASC) VISIBLE;

CREATE INDEX `fk_EventoCultural_has_Persona_EventoCultural3_idx` ON `mydb`.`EventoCultural_participar_Persona` (`EventoCultural_idEventoCultural` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ConvocGAI (GrArtInst)`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ConvocGAI (GrArtInst)` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ConvocGAI (GrArtInst)` (
  `idConvocGAI` INT NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Disciplina` VARCHAR(45) NOT NULL,
  `Docente_Docente_id` INT NOT NULL,
  PRIMARY KEY (`idConvocGAI`),
  CONSTRAINT `fk_ConvocGAI (GrArtInst)_Docente1`
    FOREIGN KEY (`Docente_Docente_id`)
    REFERENCES `mydb`.`Docente` (`docID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ConvocGAI (GrArtInst)_Docente1_idx` ON `mydb`.`ConvocGAI (GrArtInst)` (`Docente_Docente_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ConvocGAI (GrArtInst)_has_Actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ConvocGAI (GrArtInst)_has_Actividad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ConvocGAI (GrArtInst)_has_Actividad` (
  `ConvocGAI (GrArtInst)_idConvocGAI` INT NOT NULL,
  `Actividad_idActividad` INT NOT NULL,
  PRIMARY KEY (`ConvocGAI (GrArtInst)_idConvocGAI`, `Actividad_idActividad`),
  CONSTRAINT `fk_ConvocGAI (GrArtInst)_has_Actividad_ConvocGAI (GrArtInst)1`
    FOREIGN KEY (`ConvocGAI (GrArtInst)_idConvocGAI`)
    REFERENCES `mydb`.`ConvocGAI (GrArtInst)` (`idConvocGAI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConvocGAI (GrArtInst)_has_Actividad_Actividad1`
    FOREIGN KEY (`Actividad_idActividad`)
    REFERENCES `mydb`.`Actividad` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ConvocGAI (GrArtInst)_has_Actividad_Actividad1_idx` ON `mydb`.`ConvocGAI (GrArtInst)_has_Actividad` (`Actividad_idActividad` ASC) VISIBLE;

CREATE INDEX `fk_ConvocGAI (GrArtInst)_has_Actividad_ConvocGAI (GrArtInst_idx` ON `mydb`.`ConvocGAI (GrArtInst)_has_Actividad` (`ConvocGAI (GrArtInst)_idConvocGAI` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ConvocGAI_has_EstudianteAspirante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ConvocGAI_has_EstudianteAspirante` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ConvocGAI_has_EstudianteAspirante` (
  `ConvocGAI (GrArtInst)_idConvocGAI` INT NOT NULL,
  `Estudiante_Estudiante_id` INT NOT NULL,
  `Talento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ConvocGAI (GrArtInst)_idConvocGAI`, `Estudiante_Estudiante_id`),
  CONSTRAINT `fk_ConvocGAI (GrArtInst)_has_Estudiante_ConvocGAI (GrArtInst)1`
    FOREIGN KEY (`ConvocGAI (GrArtInst)_idConvocGAI`)
    REFERENCES `mydb`.`ConvocGAI (GrArtInst)` (`idConvocGAI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConvocGAI (GrArtInst)_has_Estudiante_Estudiante1`
    FOREIGN KEY (`Estudiante_Estudiante_id`)
    REFERENCES `mydb`.`Estudiante` (`estID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ConvocGAI (GrArtInst)_has_Estudiante_Estudiante1_idx` ON `mydb`.`ConvocGAI_has_EstudianteAspirante` (`Estudiante_Estudiante_id` ASC) VISIBLE;

CREATE INDEX `fk_ConvocGAI (GrArtInst)_has_Estudiante_ConvocGAI (GrArtIns_idx` ON `mydb`.`ConvocGAI_has_EstudianteAspirante` (`ConvocGAI (GrArtInst)_idConvocGAI` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ConvocGAI_has_EstudianteAceptado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ConvocGAI_has_EstudianteAceptado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ConvocGAI_has_EstudianteAceptado` (
  `ConvocGAI (GrArtInst)_idConvocGAI` INT NOT NULL,
  `Estudiante_Estudiante_id` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`ConvocGAI (GrArtInst)_idConvocGAI`, `Estudiante_Estudiante_id`),
  CONSTRAINT `fk_ConvocGAI (GrArtInst)_has_Estudiante_ConvocGAI (GrArtInst)2`
    FOREIGN KEY (`ConvocGAI (GrArtInst)_idConvocGAI`)
    REFERENCES `mydb`.`ConvocGAI (GrArtInst)` (`idConvocGAI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConvocGAI (GrArtInst)_has_Estudiante_Estudiante2`
    FOREIGN KEY (`Estudiante_Estudiante_id`)
    REFERENCES `mydb`.`Estudiante` (`estID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ConvocGAI (GrArtInst)_has_Estudiante_Estudiante2_idx` ON `mydb`.`ConvocGAI_has_EstudianteAceptado` (`Estudiante_Estudiante_id` ASC) VISIBLE;

CREATE INDEX `fk_ConvocGAI (GrArtInst)_has_Estudiante_ConvocGAI (GrArtIns_idx` ON `mydb`.`ConvocGAI_has_EstudianteAceptado` (`ConvocGAI (GrArtInst)_idConvocGAI` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `idProducto` INT NOT NULL,
  `Precio` DOUBLE NOT NULL,
  `Detalle` VARCHAR(45) NOT NULL,
  `TotalVendido` DOUBLE NOT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto_ofrecer_TiendaBienestarUN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Producto_ofrecer_TiendaBienestarUN` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Producto_ofrecer_TiendaBienestarUN` (
  `Producto_idProducto` INT NOT NULL,
  `TiendaBienestarUN_idTiendaBienestarUN` INT NOT NULL,
  `Descuento` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Producto_idProducto`, `TiendaBienestarUN_idTiendaBienestarUN`),
  CONSTRAINT `fk_Producto_has_TiendaBienestarUN_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_TiendaBienestarUN_TiendaBienestarUN1`
    FOREIGN KEY (`TiendaBienestarUN_idTiendaBienestarUN`)
    REFERENCES `mydb`.`TiendaBienestarUN` (`idTiendaBienestarUN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Producto_has_TiendaBienestarUN_TiendaBienestarUN1_idx` ON `mydb`.`Producto_ofrecer_TiendaBienestarUN` (`TiendaBienestarUN_idTiendaBienestarUN` ASC) VISIBLE;

CREATE INDEX `fk_Producto_has_TiendaBienestarUN_Producto1_idx` ON `mydb`.`Producto_ofrecer_TiendaBienestarUN` (`Producto_idProducto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Factura` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Factura` (
  `idFactura` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `Detalle` VARCHAR(50) NOT NULL,
  `TiendaBienestarUN_idTiendaBienestarUN` INT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idFactura`),
  CONSTRAINT `fk_Factura_TiendaBienestarUN1`
    FOREIGN KEY (`TiendaBienestarUN_idTiendaBienestarUN`)
    REFERENCES `mydb`.`TiendaBienestarUN` (`idTiendaBienestarUN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Factura_TiendaBienestarUN1_idx` ON `mydb`.`Factura` (`TiendaBienestarUN_idTiendaBienestarUN` ASC) VISIBLE;

CREATE INDEX `fk_Factura_Persona1_idx` ON `mydb`.`Factura` (`Persona_idPersona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Factura_vender_Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Factura_vender_Producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Factura_vender_Producto` (
  `Factura_idFactura` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  PRIMARY KEY (`Factura_idFactura`, `Producto_idProducto`),
  CONSTRAINT `fk_Factura_has_Producto_Factura1`
    FOREIGN KEY (`Factura_idFactura`)
    REFERENCES `mydb`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_has_Producto_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Factura_has_Producto_Producto1_idx` ON `mydb`.`Factura_vender_Producto` (`Producto_idProducto` ASC) VISIBLE;

CREATE INDEX `fk_Factura_has_Producto_Factura1_idx` ON `mydb`.`Factura_vender_Producto` (`Factura_idFactura` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`GestionEconomica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GestionEconomica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GestionEconomica` (
  `idGesEcono` INT NOT NULL,
  `Plazo (meses)` INT NOT NULL,
  `Estudiante_Estudiante_id` INT NOT NULL,
  PRIMARY KEY (`idGesEcono`, `Estudiante_Estudiante_id`),
  CONSTRAINT `fk_GestionEconomica_Estudiante1`
    FOREIGN KEY (`Estudiante_Estudiante_id`)
    REFERENCES `mydb`.`Estudiante` (`estID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_GestionEconomica_Estudiante1_idx` ON `mydb`.`GestionEconomica` (`Estudiante_Estudiante_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`AuxilioEconomico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AuxilioEconomico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AuxilioEconomico` (
  `idAuxEcono` INT NOT NULL,
  `Monto` DOUBLE NOT NULL,
  `horCorrespon` INT NOT NULL,
  PRIMARY KEY (`idAuxEcono`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GestionAlojamiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GestionAlojamiento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GestionAlojamiento` (
  `idAuxEcono` INT NOT NULL,
  `Direccion` VARCHAR(55) NOT NULL,
  `Monto` DOUBLE NOT NULL,
  `horCorrespon` INT NOT NULL,
  PRIMARY KEY (`idAuxEcono`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GestionTransporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GestionTransporte` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GestionTransporte` (
  `idGesTransp` INT NOT NULL,
  `Monto` DOUBLE NOT NULL,
  `horCorrespon` INT NOT NULL,
  PRIMARY KEY (`idGesTransp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FomentoEmprendimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FomentoEmprendimiento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`FomentoEmprendimiento` (
  `idFomEmprende` INT NOT NULL,
  `NomEmprendimiento` VARCHAR(50) NOT NULL,
  `AreAcademica` VARCHAR(30) NOT NULL,
  `Tema` VARCHAR(30) NOT NULL,
  `Descripcion` VARCHAR(60) NOT NULL,
  `Lider_Estudiante_id` INT NOT NULL,
  `Lider_Docente_id` INT NOT NULL,
  `Monto` DOUBLE NOT NULL,
  PRIMARY KEY (`idFomEmprende`),
  CONSTRAINT `fk_FomentoEmprendimiento_Estudiante1`
    FOREIGN KEY (`Lider_Estudiante_id`)
    REFERENCES `mydb`.`Estudiante` (`estID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FomentoEmprendimiento_Docente1`
    FOREIGN KEY (`Lider_Docente_id`)
    REFERENCES `mydb`.`Docente` (`docID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_FomentoEmprendimiento_Estudiante1_idx` ON `mydb`.`FomentoEmprendimiento` (`Lider_Estudiante_id` ASC) VISIBLE;

CREATE INDEX `fk_FomentoEmprendimiento_Docente1_idx` ON `mydb`.`FomentoEmprendimiento` (`Lider_Docente_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Corresponsabilidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Corresponsabilidad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Corresponsabilidad` (
  `idCorresp` INT NOT NULL,
  `FecSolicitud` DATE NOT NULL,
  `FecLimCumplir` DATE NOT NULL,
  `HorAsignadas` INT NOT NULL,
  `HorRealizadas` INT NOT NULL,
  `GestionEconomica_idGesEcono` INT NOT NULL,
  `AuxilioEconomico_idAuxEcono` INT NULL,
  `GestionAlojamiento_idAuxEcono` INT NULL,
  `GestionTransporte_idGesTransp` INT NULL,
  `FomentoEmprendimiento_idFomEmprende` INT NULL,
  PRIMARY KEY (`idCorresp`, `GestionEconomica_idGesEcono`),
  CONSTRAINT `fk_Corresponsabilidad_GestionEconomica1`
    FOREIGN KEY (`GestionEconomica_idGesEcono`)
    REFERENCES `mydb`.`GestionEconomica` (`idGesEcono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Corresponsabilidad_AuxilioEconomico1`
    FOREIGN KEY (`AuxilioEconomico_idAuxEcono`)
    REFERENCES `mydb`.`AuxilioEconomico` (`idAuxEcono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Corresponsabilidad_GestionAlojamiento1`
    FOREIGN KEY (`GestionAlojamiento_idAuxEcono`)
    REFERENCES `mydb`.`GestionAlojamiento` (`idAuxEcono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Corresponsabilidad_GestionTransporte1`
    FOREIGN KEY (`GestionTransporte_idGesTransp`)
    REFERENCES `mydb`.`GestionTransporte` (`idGesTransp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Corresponsabilidad_FomentoEmprendimiento1`
    FOREIGN KEY (`FomentoEmprendimiento_idFomEmprende`)
    REFERENCES `mydb`.`FomentoEmprendimiento` (`idFomEmprende`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Corresponsabilidad_GestionEconomica1_idx` ON `mydb`.`Corresponsabilidad` (`GestionEconomica_idGesEcono` ASC) VISIBLE;

CREATE INDEX `fk_Corresponsabilidad_AuxilioEconomico1_idx` ON `mydb`.`Corresponsabilidad` (`AuxilioEconomico_idAuxEcono` ASC) VISIBLE;

CREATE INDEX `fk_Corresponsabilidad_GestionAlojamiento1_idx` ON `mydb`.`Corresponsabilidad` (`GestionAlojamiento_idAuxEcono` ASC) VISIBLE;

CREATE INDEX `fk_Corresponsabilidad_GestionTransporte1_idx` ON `mydb`.`Corresponsabilidad` (`GestionTransporte_idGesTransp` ASC) VISIBLE;

CREATE INDEX `fk_Corresponsabilidad_FomentoEmprendimiento1_idx` ON `mydb`.`Corresponsabilidad` (`FomentoEmprendimiento_idFomEmprende` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`HoraRealizada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`HoraRealizada` ;

CREATE TABLE IF NOT EXISTS `mydb`.`HoraRealizada` (
  `idHoraRealizada` INT NOT NULL,
  `Lugar` VARCHAR(30) NOT NULL,
  `Fecha` DATE NOT NULL,
  `ActRealizada` VARCHAR(50) NOT NULL,
  `Corresponsabilidad_idCorresp` INT NOT NULL,
  `Auditor_idPersona` INT NOT NULL,
  PRIMARY KEY (`idHoraRealizada`, `Corresponsabilidad_idCorresp`),
  CONSTRAINT `fk_HoraRealizada_Corresponsabilidad1`
    FOREIGN KEY (`Corresponsabilidad_idCorresp`)
    REFERENCES `mydb`.`Corresponsabilidad` (`idCorresp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HoraRealizada_Persona1`
    FOREIGN KEY (`Auditor_idPersona`)
    REFERENCES `mydb`.`Persona` (`perID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_HoraRealizada_Corresponsabilidad1_idx` ON `mydb`.`HoraRealizada` (`Corresponsabilidad_idCorresp` ASC) VISIBLE;

CREATE INDEX `fk_HoraRealizada_Persona1_idx` ON `mydb`.`HoraRealizada` (`Auditor_idPersona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`GestionAlimentaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GestionAlimentaria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GestionAlimentaria` (
  `idGesAlime` INT NOT NULL,
  `comedor` VARCHAR(10) NOT NULL,
  `descuento` INT NOT NULL,
  `horCorrespon` INT NOT NULL,
  `Beneficio` ENUM("DESAYUNO", "ALMUERZO", "CENA") NOT NULL,
  PRIMARY KEY (`idGesAlime`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GestionAlimentaria_has_Corresponsabilidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`GestionAlimentaria_has_Corresponsabilidad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`GestionAlimentaria_has_Corresponsabilidad` (
  `GestionAlimentaria_idGesAlime` INT NOT NULL,
  `Corresponsabilidad_idCorresp` INT NOT NULL,
  `GesEcon_idGesEcono` INT NOT NULL,
  PRIMARY KEY (`GestionAlimentaria_idGesAlime`, `Corresponsabilidad_idCorresp`, `GesEcon_idGesEcono`),
  CONSTRAINT `fk_GestionAlimentaria_has_Corresponsabilidad_GestionAlimentar1`
    FOREIGN KEY (`GestionAlimentaria_idGesAlime`)
    REFERENCES `mydb`.`GestionAlimentaria` (`idGesAlime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GestionAlimentaria_has_Corresponsabilidad_Corresponsabilid1`
    FOREIGN KEY (`Corresponsabilidad_idCorresp` , `GesEcon_idGesEcono`)
    REFERENCES `mydb`.`Corresponsabilidad` (`idCorresp` , `GestionEconomica_idGesEcono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_GestionAlimentaria_has_Corresponsabilidad_Corresponsabil_idx` ON `mydb`.`GestionAlimentaria_has_Corresponsabilidad` (`Corresponsabilidad_idCorresp` ASC, `GesEcon_idGesEcono` ASC) VISIBLE;

CREATE INDEX `fk_GestionAlimentaria_has_Corresponsabilidad_GestionAliment_idx` ON `mydb`.`GestionAlimentaria_has_Corresponsabilidad` (`GestionAlimentaria_idGesAlime` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`FallaAmilentacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FallaAmilentacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`FallaAmilentacion` (
  `idFallAlim` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Beneficio` ENUM("DESAYUNO", "ALMUERZO", "CENA") NOT NULL,
  `GestAlim_has_Corr` INT NOT NULL,
  `Corres_idCorresp` INT NOT NULL,
  `GestionEconomica_idGesEcono` INT NOT NULL,
  PRIMARY KEY (`idFallAlim`, `GestAlim_has_Corr`, `Corres_idCorresp`, `GestionEconomica_idGesEcono`),
  CONSTRAINT `fk_FallaAmilentacion_GestionAlimentaria_has_Corresponsabilidad1`
    FOREIGN KEY (`GestAlim_has_Corr` , `Corres_idCorresp` , `GestionEconomica_idGesEcono`)
    REFERENCES `mydb`.`GestionAlimentaria_has_Corresponsabilidad` (`GestionAlimentaria_idGesAlime` , `Corresponsabilidad_idCorresp` , `GesEcon_idGesEcono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_FallaAmilentacion_GestionAlimentaria_has_Corresponsabili_idx` ON `mydb`.`FallaAmilentacion` (`GestAlim_has_Corr` ASC, `Corres_idCorresp` ASC, `GestionEconomica_idGesEcono` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Equipo_FomEmp_perr_Estud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Equipo_FomEmp_perr_Estud` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Equipo_FomEmp_perr_Estud` (
  `FomentoEmprendimiento_idFomEmprende` INT NOT NULL,
  `Estudiante_Estudiante_id` INT NOT NULL,
  `rol` VARCHAR(20) NULL,
  PRIMARY KEY (`FomentoEmprendimiento_idFomEmprende`, `Estudiante_Estudiante_id`),
  CONSTRAINT `fk_FomentoEmprendimiento_has_Estudiante_FomentoEmprendimiento1`
    FOREIGN KEY (`FomentoEmprendimiento_idFomEmprende`)
    REFERENCES `mydb`.`FomentoEmprendimiento` (`idFomEmprende`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FomentoEmprendimiento_has_Estudiante_Estudiante1`
    FOREIGN KEY (`Estudiante_Estudiante_id`)
    REFERENCES `mydb`.`Estudiante` (`estID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_FomentoEmprendimiento_has_Estudiante_Estudiante1_idx` ON `mydb`.`Equipo_FomEmp_perr_Estud` (`Estudiante_Estudiante_id` ASC) VISIBLE;

CREATE INDEX `fk_FomentoEmprendimiento_has_Estudiante_FomentoEmprendimien_idx` ON `mydb`.`Equipo_FomEmp_perr_Estud` (`FomentoEmprendimiento_idFomEmprende` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`AlianzasEstrategicas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`AlianzasEstrategicas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`AlianzasEstrategicas` (
  `idFallAlim` INT NOT NULL,
  `NomAlianza` VARCHAR(40) NOT NULL,
  `Entidad` VARCHAR(50) NOT NULL,
  `Estado` ENUM("ACTIVO", "NO ACTIVO") NOT NULL,
  `Descripcion` VARCHAR(55) NOT NULL,
  `ConBieneUniv_idConBieneUniv` INT NOT NULL,
  PRIMARY KEY (`idFallAlim`),
  CONSTRAINT `fk_AlianzasEstrategicas_ConBieneUniv1`
    FOREIGN KEY (`ConBieneUniv_idConBieneUniv`)
    REFERENCES `mydb`.`ConBieneUniv` (`idConBieneUniv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_AlianzasEstrategicas_ConBieneUniv1_idx` ON `mydb`.`AlianzasEstrategicas` (`ConBieneUniv_idConBieneUniv` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Programa Área Deportes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Programa Área Deportes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Programa Área Deportes` (
  `idNombrePrograma` VARCHAR(70) NOT NULL,
  `Extensión` INT NOT NULL,
  `Actividad Física y Deportes_idNombreArea` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idNombrePrograma`, `Actividad Física y Deportes_idNombreArea`),
  CONSTRAINT `fk_Programa Área Deportes_Actividad Física y Deportes1`
    FOREIGN KEY (`Actividad Física y Deportes_idNombreArea`)
    REFERENCES `mydb`.`Actividad Física y Deportes` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Programa Área Deportes_Actividad Física y Deportes1_idx` ON `mydb`.`Programa Área Deportes` (`Actividad Física y Deportes_idNombreArea` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`TorneoInterno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TorneoInterno` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TorneoInterno` (
  `idTorneoInterno` INT NOT NULL,
  `Periodo` VARCHAR(10) NOT NULL,
  `Sede/Facultad` VARCHAR(60) NOT NULL,
  `Deporte` VARCHAR(35) NOT NULL,
  `NombreTorneo` VARCHAR(90) NOT NULL,
  `Estado` TINYINT NOT NULL,
  `Modalidad` VARCHAR(45) NULL,
  `Rama` VARCHAR(45) NOT NULL,
  `Nivel` VARCHAR(45) NULL,
  `FechaInicio` DATE NOT NULL,
  `FechaFinalización` DATE NOT NULL,
  `Programa Área Deportes_idNombrePrograma` VARCHAR(70) NOT NULL,
  `Programa Área Deportes_Actividad Física y Deportes_idNombreArea` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Programa Área Deportes_idNombrePrograma`, `Programa Área Deportes_Actividad Física y Deportes_idNombreArea`, `idTorneoInterno`),
  CONSTRAINT `fk_TorneoInterno_Programa Área Deportes1`
    FOREIGN KEY (`Programa Área Deportes_idNombrePrograma` , `Programa Área Deportes_Actividad Física y Deportes_idNombreArea`)
    REFERENCES `mydb`.`Programa Área Deportes` (`idNombrePrograma` , `Actividad Física y Deportes_idNombreArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TorneoInterno_Programa Área Deportes1_idx` ON `mydb`.`TorneoInterno` (`Programa Área Deportes_idNombrePrograma` ASC, `Programa Área Deportes_Actividad Física y Deportes_idNombreArea` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`CursoLibre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CursoLibre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CursoLibre` (
  `idCursoLibre` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `TipoCurso` VARCHAR(45) NOT NULL,
  `Período` VARCHAR(30) NOT NULL,
  `Condición` VARCHAR(45) NOT NULL,
  `Programa Área Deportes_idNombrePrograma` VARCHAR(70) NOT NULL,
  `Programa Área Deportes_Actividad Física y Deportes_idNombreArea` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idCursoLibre`, `Programa Área Deportes_idNombrePrograma`, `Programa Área Deportes_Actividad Física y Deportes_idNombreArea`),
  CONSTRAINT `fk_CursoLibre_Programa Área Deportes1`
    FOREIGN KEY (`Programa Área Deportes_idNombrePrograma` , `Programa Área Deportes_Actividad Física y Deportes_idNombreArea`)
    REFERENCES `mydb`.`Programa Área Deportes` (`idNombrePrograma` , `Actividad Física y Deportes_idNombreArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CursoLibre_Programa Área Deportes1_idx` ON `mydb`.`CursoLibre` (`Programa Área Deportes_idNombrePrograma` ASC, `Programa Área Deportes_Actividad Física y Deportes_idNombreArea` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ConcocatoriaSelección`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ConcocatoriaSelección` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ConcocatoriaSelección` (
  `idConcocatoriaSelección` INT NOT NULL,
  `Deporte` VARCHAR(45) NOT NULL,
  `Fecha` DATETIME(20) NOT NULL,
  `Lugar` VARCHAR(50) NOT NULL,
  `Hora` TIME NOT NULL,
  `Programa Área Deportes_idNombrePrograma` VARCHAR(70) NOT NULL,
  `Programa Área Deportes_Actividad Física y Deportes_idNombreArea` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idConcocatoriaSelección`, `Programa Área Deportes_idNombrePrograma`, `Programa Área Deportes_Actividad Física y Deportes_idNombreArea`),
  CONSTRAINT `fk_ConcocatoriaSelección_Programa Área Deportes1`
    FOREIGN KEY (`Programa Área Deportes_idNombrePrograma` , `Programa Área Deportes_Actividad Física y Deportes_idNombreArea`)
    REFERENCES `mydb`.`Programa Área Deportes` (`idNombrePrograma` , `Actividad Física y Deportes_idNombreArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ConcocatoriaSelección_Programa Área Deportes1_idx` ON `mydb`.`ConcocatoriaSelección` (`Programa Área Deportes_idNombrePrograma` ASC, `Programa Área Deportes_Actividad Física y Deportes_idNombreArea` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ProgramaÁreaAcompañamiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ProgramaÁreaAcompañamiento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ProgramaÁreaAcompañamiento` (
  `Nombre` VARCHAR(65) NOT NULL,
  `Extensión` INT NOT NULL,
  `AcompañamientoIntegral_idNombreArea` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Nombre`, `AcompañamientoIntegral_idNombreArea`),
  CONSTRAINT `fk_ProgramaÁreaAcompañamiento_AcompañamientoIntegral1`
    FOREIGN KEY (`AcompañamientoIntegral_idNombreArea`)
    REFERENCES `mydb`.`AcompañamientoIntegral` (`idNombreArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ProgramaÁreaAcompañamiento_AcompañamientoIntegral1_idx` ON `mydb`.`ProgramaÁreaAcompañamiento` (`AcompañamientoIntegral_idNombreArea` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Evento/Taller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Evento/Taller` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Evento/Taller` (
  `idEvento/Taller` INT NOT NULL,
  `Nombre` VARCHAR(60) NOT NULL,
  `Tipo Evento/Taller` VARCHAR(45) NOT NULL,
  `Descripcion` LONGTEXT NOT NULL,
  `ProgramaÁreaAcompañamiento_Nombre` VARCHAR(65) NOT NULL,
  `ProgramaÁreaAcompañamiento_AcompañamientoIntegral_idNombreArea` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idEvento/Taller`, `ProgramaÁreaAcompañamiento_Nombre`, `ProgramaÁreaAcompañamiento_AcompañamientoIntegral_idNombreArea`),
  CONSTRAINT `fk_Evento/Taller_ProgramaÁreaAcompañamiento1`
    FOREIGN KEY (`ProgramaÁreaAcompañamiento_Nombre` , `ProgramaÁreaAcompañamiento_AcompañamientoIntegral_idNombreArea`)
    REFERENCES `mydb`.`ProgramaÁreaAcompañamiento` (`Nombre` , `AcompañamientoIntegral_idNombreArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Evento/Taller_ProgramaÁreaAcompañamiento1_idx` ON `mydb`.`Evento/Taller` (`ProgramaÁreaAcompañamiento_Nombre` ASC, `ProgramaÁreaAcompañamiento_AcompañamientoIntegral_idNombreArea` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`PuntoDeContacto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PuntoDeContacto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PuntoDeContacto` (
  `idPuntoDeContacto` INT NOT NULL,
  `TipoDeContacto` VARCHAR(45) NOT NULL,
  `ProgramaÁreaAcompañamiento_Nombre` VARCHAR(65) NOT NULL,
  `ProgramaÁreaAcompañamiento_AcompañamientoIntegral_idNombreArea` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idPuntoDeContacto`, `ProgramaÁreaAcompañamiento_Nombre`, `ProgramaÁreaAcompañamiento_AcompañamientoIntegral_idNombreArea`),
  CONSTRAINT `fk_PuntoDeContacto_ProgramaÁreaAcompañamiento1`
    FOREIGN KEY (`ProgramaÁreaAcompañamiento_Nombre` , `ProgramaÁreaAcompañamiento_AcompañamientoIntegral_idNombreArea`)
    REFERENCES `mydb`.`ProgramaÁreaAcompañamiento` (`Nombre` , `AcompañamientoIntegral_idNombreArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PuntoDeContacto_ProgramaÁreaAcompañamiento1_idx` ON `mydb`.`PuntoDeContacto` (`ProgramaÁreaAcompañamiento_Nombre` ASC, `ProgramaÁreaAcompañamiento_AcompañamientoIntegral_idNombreArea` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ProyectoDeAcompañamiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ProyectoDeAcompañamiento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ProyectoDeAcompañamiento` (
  `idProyectoDeAcompañamiento` INT NOT NULL,
  `Nombre` VARCHAR(60) NOT NULL,
  `Ejecución` VARCHAR(100) NOT NULL,
  `FechaInicio` DATE NOT NULL,
  `FechaFinalización` DATE NOT NULL,
  `Presupuesto` VARCHAR(1000) NOT NULL,
  `ProgramaÁreaAcompañamiento_Nombre` VARCHAR(65) NOT NULL,
  `ProgramaÁreaAcompañamiento_AcompañamientoIntegral_idNombreArea` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idProyectoDeAcompañamiento`, `ProgramaÁreaAcompañamiento_Nombre`, `ProgramaÁreaAcompañamiento_AcompañamientoIntegral_idNombreArea`),
  CONSTRAINT `fk_ProyectoDeAcompañamiento_ProgramaÁreaAcompañamiento1`
    FOREIGN KEY (`ProgramaÁreaAcompañamiento_Nombre` , `ProgramaÁreaAcompañamiento_AcompañamientoIntegral_idNombreArea`)
    REFERENCES `mydb`.`ProgramaÁreaAcompañamiento` (`Nombre` , `AcompañamientoIntegral_idNombreArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ProyectoDeAcompañamiento_ProgramaÁreaAcompañamiento1_idx` ON `mydb`.`ProyectoDeAcompañamiento` (`ProgramaÁreaAcompañamiento_Nombre` ASC, `ProgramaÁreaAcompañamiento_AcompañamientoIntegral_idNombreArea` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Contacto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Contacto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Contacto` (
  `NombreÁrea` VARCHAR(90) NOT NULL,
  `NombreContacto` VARCHAR(60) NOT NULL,
  `Teléfono` INT NOT NULL,
  `Extensión` INT NOT NULL,
  `CorreoElectrónico` VARCHAR(50) NOT NULL,
  `ConBieneID` INT NULL,
  PRIMARY KEY (`NombreÁrea`),
  CONSTRAINT `fk_Contacto_ConBieneUniv1`
    FOREIGN KEY (`ConBieneID`)
    REFERENCES `mydb`.`ConBieneUniv` (`idConBieneUniv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Contacto_ConBieneUniv1_idx` ON `mydb`.`Contacto` (`ConBieneID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Anexos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Anexos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Anexos` (
  `Normatividad_id` INT NOT NULL,
  `aneNombre` VARCHAR(45) NOT NULL,
  `aneLink` VARCHAR(45) NOT NULL,
  CONSTRAINT `fk_Anexos_Normatividad1`
    FOREIGN KEY (`Normatividad_id`)
    REFERENCES `mydb`.`Normatividad` (`idNormatividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Anexos_Normatividad1_idx` ON `mydb`.`Anexos` (`Normatividad_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`estTieneRepEst`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estTieneRepEst` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estTieneRepEst` (
  `Estudiante_estID` INT NOT NULL,
  `ReprEstudiantil_estID` INT NOT NULL,
  PRIMARY KEY (`Estudiante_estID`, `ReprEstudiantil_estID`),
  CONSTRAINT `fk_Estudiante_has_ReprEstudiantil_Estudiante1`
    FOREIGN KEY (`Estudiante_estID`)
    REFERENCES `mydb`.`Estudiante` (`estID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estTieneRepEst_ReprEstudiantil1`
    FOREIGN KEY (`ReprEstudiantil_estID`)
    REFERENCES `mydb`.`ReprEstudiantil` (`estID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Estudiante_has_ReprEstudiantil_Estudiante1_idx` ON `mydb`.`estTieneRepEst` (`Estudiante_estID` ASC) VISIBLE;

CREATE INDEX `fk_estTieneRepEst_ReprEstudiantil1_idx` ON `mydb`.`estTieneRepEst` (`ReprEstudiantil_estID` ASC) VISIBLE;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

USE `mydb`;
DROP  IF EXISTS `mydb`.`routine1`;

DELIMITER $$
USE `mydb`$$
$$

DELIMITER ;

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
DROP VIEW IF EXISTS `mydb`.`view1` ;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
